### ISSUE TITLE
Advise for how to create multi static IP address when using bridge

### ISSUE THREAD

**Issue by LavBU** [MonolithProjects/terraform-libvirt-vm#23]
Hi,

I'm using this network.cfg file, to create 3 static IP address:

```
network:
  version: 1
  config:
    - type: physical
      name: eth0
      mtu: 1500
      subnets:
        - type: static
          address:  10.94.13.27/22
          gateway: 10.94.13.1
          dns_nameservers: [ 10.94.12.59 ]
    - type: physical
      name: eth1
      mtu: 9000
      subnets:
        - type: static
          address:  10.94.16.15/22
    - type: physical
      name: eth2
      mtu: 9000
      subnets:
        - type: static
          address:  10.94.20.15/22
    - type: route
      destination: 0.0.0.0/0
      gateway: 10.94.13.1
      metric: 3
```
And using this libvirt_network in main.tf to setup network bridges:

```
resource "libvirt_network" "vm_public_network" {
  name = "${var.VM_HOSTNAME}_network"
  mode = "bridge"
  bridge = "br_v12"
  dhcp {
   enabled = false
  }
  dns {
   enabled = true
  }
}
```
By that, I have the VM up and running, but with one "eth0" interface only (and one IP address).
I can SSH to this IP, but the other interfaces are not created.
It seems that the root cause is the missing of the additional "bridge", but didn't find the right syntax for multi bridge.

there is this section also, in regards to network_id, but not sure how to declare more than one network_id:

```
resource "libvirt_domain" "vm" {
  count = var.VM_COUNT
  name = "${var.VM_HOSTNAME}-${count.index}"
  memory = var.VMEM
  vcpu = var.VCPU
  cloudinit = "${libvirt_cloudinit_disk.cloudinit.id}"
  qemu_agent = true
  network_interface {
    network_id = "${libvirt_network.vm_public_network.id}"
    network_name = "${libvirt_network.vm_public_network.name}"
  }
```
Appreciate any help.

Thanks,
Lavi
